# This dockerfile is made for BOOK<Learn c the hardway>, a simple Linux environment on non-Linux OS as windows

FROM debian:latest
RUN apt-get update && apt-get install -y \
build-essential \
nano \
man \
&&rm -rf /var/lib/apt/lists/*

WORKDIR /home/hikaru89
